# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./API/UrlShortner.Api.csproj --configuration Release --output ./output
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        paths: ./output
        name: api-output-artifact


  
  deployto-dev:

    runs-on: ubuntu-latest
    needs: build
    environment: Development
    
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-output-artifact
          paths: ./output
      - name: Deploy to Development
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.API_Name }}
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ./output
          slot-name: Production